# Site settings
title: wefixit Creative Web Design Studio
email: info@wefixit.gr
description: > We are a small UX driven design studio in Greece. We strive to get involved in
projects that inspire our creativity and bring results through thoughtful design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_url: http://twitter.com/me
facebook_url: http://facebook.com/me
g+_url: http://plus.google.com/me
instagram_url: http://instagram.com/me
linkedin_url: http://linkedin.com/me
skype_url: skype?add

# Build settings
markdown: kramdown
